### PR TITLE
Fix syntax!

### PR DESCRIPTION
**Pull request by sagarshah1729**

### CODE REVIEW

**Comment by xdevs23** [comment]
Damn how could I miss that

**Comment by sagarshah1729** [comment]
Stuff Happens!!😂

**Comment by xdevs23** [comment]
Thanks

**Comment by xdevs23** [comment]
https://github.com/halogenOS/android_packages_apps_OTAUpdates/commit/add3dce901b4af3154d5c2b85cc80b9d532de72b

**Pull request closed without merging**
